schema = 3

[mod]
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.2"
    hash = "sha256-mRa+6qEi5joqQao13ZFogmq67rOQzHCVbCCjKA+HKEc="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
